### ISSUE TITLE
Consider using ManuallyDrop

### ISSUE THREAD

**Issue by SoniEx2** [jyn514/size-of-trait#2]
As an experiment, consider using `ManuallyDrop` instead of relying purely on `[T; 0]`. Something like `ManuallyDrop<[T; 0]>` should work. See also the discussion in rust-lang/rust#110288

**Comment by jyn514** [comment]
that fcp was closed as explicitly not wanting to add a dropck requirement https://github.com/rust-lang/rust/issues/110288#issuecomment-1517872777
